---
# Load policy into root branch
# This policy defines a demo organization that uses GitLab runners

# Define Admins, create admins group, create admin01 user
- !group
  id: admins 
  owner: !user admin

- !user
  id: admin01
  owner: !group admins

- !permit
  role: !group admins
  privileges: [read,update,create]
  resource: !policy root

- !grant
  role: !group admins
  members: 
    - !user admin01

# Define gitlab branch, create users, hosts, groups, layers, variables
- !policy
  id: gitlab
  owner: !group admins

# gitlab/managers group will admin everything under gitlab branch
- !group
  id: gitlab/managers
  owner: !group admins

- !permit
  role: !group gitlab/managers
  privileges: [read,update,create]
  resource: !policy gitlab

- !permit
  role: !group gitlab/managers
  privileges: [read,update,create]
  resource: !group gitlab/managers

- !user
  id: gitlab-manager01
  owner: !group gitlab/managers

- !grant
  role: !group gitlab/managers
  members: 
    - !user gitlab-manager01
